export interface IAuxTable {
    header1 : string
    header2 : string
    header3 : string
    cell11 : string
    cell12 : string
    cell13 : string
    cell21 : string
    cell22 : string
    cell23 : string
    cell31 : string
    cell32 : string
    cell33 : string
    cell41 : string
    cell42 : string
    cell43 : string
    cell51 : string
    cell52 : string
    cell53 : string
    cell61 : string
    cell62 : string
    cell63 : string
    cell71 : string
    cell72 : string
    cell73 : string
    cell81 : string
    cell82 : string
    cell83 : string
    cell91 : string
    cell92 : string
    cell93 : string
    cell101 : string
    cell102 : string
    cell103 : string
}